export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const POST_ACTIVITY_SUCCESS = 'POST_ACTIVITY_SUCCESS';
export const POST_ACTIVITY_FAIL = 'POST_ACTIVITY_FAIL';
export const LOAD_DATA = 'LOAD_DATA';



